modLoader="javafml"
loaderVersion="47"
license="CC BY-NC-SA 4.0 Deed "
issueTrackerURL="https://github.com/Lance5057/Butchercraft/issues"

[[mods]]
modId="butchercraft"
version="2.6.0"
displayName="Butchercraft"
displayURL="https://github.com/Lance5057/Butchercraft"
authors="Alan199921, DivineAspect, Skysom, FreneticScribbler, Lanse505, Belathus, RoyalJelly, ParadigmOne, unilock"
description='''Killing an animal nets barely a few bits, maybe some meat and a few leathers, and then the rest just disappears. Such a waste!'''
enumExtensions="META-INF/enumextensions.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.butchercraft]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.butchercraft]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"
